// <auto-generated />
using System;
using BlockingService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlockingService.Migrations
{
    [DbContext(typeof(BlockingContext))]
    partial class BlockingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlockingService.Model.Entity.Blocking", b =>
                {
                    b.Property<Guid>("BlockerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlockedId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BlockerId", "BlockedId");

                    b.ToTable("Blocks");

                    b.HasData(
                        new
                        {
                            BlockerId = new Guid("eb78bf24-a3ab-48bf-a931-7b0c6e680bfd"),
                            BlockedId = new Guid("34a81ef8-2831-4444-8355-859d02ae2290")
                        },
                        new
                        {
                            BlockerId = new Guid("34a81ef8-2831-4444-8355-859d02ae2290"),
                            BlockedId = new Guid("eb78bf24-a3ab-48bf-a931-7b0c6e680bfd")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
