// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PostService.Entities;

namespace PostService.Migrations
{
    [DbContext(typeof(PostDbContext))]
    partial class PostDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PostService.Entities.PostHistory", b =>
                {
                    b.Property<int>("PostHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTo")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("PostHistoryId");

                    b.ToTable("PostHistories");

                    b.HasData(
                        new
                        {
                            PostHistoryId = 1,
                            DateFrom = new DateTime(2020, 5, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTo = new DateTime(2020, 10, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = new Guid("b43b4683-7d9d-413f-a6e1-f821a80c8ce4"),
                            Price = 2499.0
                        },
                        new
                        {
                            PostHistoryId = 2,
                            DateFrom = new DateTime(2020, 10, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = new Guid("b43b4683-7d9d-413f-a6e1-f821a80c8ce4"),
                            Price = 2590.0
                        },
                        new
                        {
                            PostHistoryId = 3,
                            DateFrom = new DateTime(2021, 6, 11, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = new Guid("8ccb1467-9f38-4164-88da-15882fe82e58"),
                            Price = 560.0
                        },
                        new
                        {
                            PostHistoryId = 4,
                            DateFrom = new DateTime(2021, 4, 17, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = new Guid("23d2cce9-86d7-4bff-887e-f7712b16766d"),
                            Price = 14690.0
                        },
                        new
                        {
                            PostHistoryId = 5,
                            DateFrom = new DateTime(2021, 6, 12, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = new Guid("5284a73f-1f9e-4799-a793-5a4fe4a1df56"),
                            Price = 2500.0
                        },
                        new
                        {
                            PostHistoryId = 6,
                            DateFrom = new DateTime(2021, 7, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = new Guid("54f9baf6-271e-40cb-8d80-a27980fc8b63"),
                            Price = 450.0
                        });
                });

            modelBuilder.Entity("PostService.Entities.Posts.Product", b =>
                {
                    b.Property<Guid>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PostImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            PostId = new Guid("b43b4683-7d9d-413f-a6e1-f821a80c8ce4"),
                            AccountId = new Guid("59ed7d80-39c9-42b8-a822-70ddd295914a"),
                            Category = "Sportska odeća",
                            Currency = "Rsd",
                            Description = "Adidas Essentials T-Shirt je muška majica koja je pogodna za mnoge sportske i zabavne aktivnosti. Napravljena je od prijatne mešavine prirodnih i veštačkih materijala.",
                            PostImage = "https://www.intersport.rs/media/catalog/product/cache/382907d7f48ae2519bf16cd5f39b77f9/g/k/gk9635_app_photo_front-center_white.jpg",
                            PostName = "Adidas sportska majica",
                            Price = 2590.0,
                            PublicationDate = new DateTime(2020, 5, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = "130g"
                        },
                        new
                        {
                            PostId = new Guid("8ccb1467-9f38-4164-88da-15882fe82e58"),
                            AccountId = new Guid("42b70088-9dbd-4b19-8fc7-16414e94a8a6"),
                            Category = "Mobilni telefoni",
                            Currency = "Euro",
                            Description = "Nov, neotpakovan Iphone 11 64GB. Garancija godinu dana.",
                            PostImage = "https://www.tehnomedia.rs/image/71354.jpg?tip=huge&tip_slike=0",
                            PostName = "Iphone 11",
                            Price = 560.0,
                            PublicationDate = new DateTime(2021, 6, 11, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = "194g"
                        },
                        new
                        {
                            PostId = new Guid("23d2cce9-86d7-4bff-887e-f7712b16766d"),
                            AccountId = new Guid("42b70088-9dbd-4b19-8fc7-16414e94a8a6"),
                            Category = "Patike za trčanje",
                            Currency = "Rsd",
                            Description = "Adidas adizero Boston 9 M su muške patike za trčanje koje su namenjene za trčanje po urbanim površinama. Stvorene su za vrhunske trkače. Đon je napravljen od Boost pene, a Continental guma pruža odlično prijanjanje.",
                            PostImage = "https://www.sportvision.rs/files/thumbs/files/images/slike_proizvoda/media/FY0/FY0343/images/thumbs_600/FY0343_600_600px.jpg",
                            PostName = "Adidas Adizero Boston 9",
                            Price = 14690.0,
                            PublicationDate = new DateTime(2021, 4, 17, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = "238g"
                        });
                });

            modelBuilder.Entity("PostService.Entities.Posts.Service", b =>
                {
                    b.Property<Guid>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PostImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PostId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            PostId = new Guid("5284a73f-1f9e-4799-a793-5a4fe4a1df56"),
                            AccountId = new Guid("f2f88bcd-d0a2-4fe7-a23f-df97a59731cd"),
                            Category = "Lepota i zdravlje",
                            Currency = "Rsd",
                            Description = "Zablistajte uz najnoviju šminku vrhunskog kvaliteta.",
                            PostImage = "",
                            PostName = "Šminkanje",
                            Price = 2500.0,
                            PublicationDate = new DateTime(2021, 6, 12, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PostId = new Guid("54f9baf6-271e-40cb-8d80-a27980fc8b63"),
                            AccountId = new Guid("59ed7d80-39c9-42b8-a822-70ddd295914a"),
                            Category = "Muški frizer",
                            Currency = "Rsd",
                            Description = "Zakaži svoj termin i dobij frizuru baš po tvojoj želji",
                            PostImage = "",
                            PostName = "Muško šišanje",
                            Price = 450.0,
                            PublicationDate = new DateTime(2021, 7, 7, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
