// <auto-generated />
using System;
using FollowingService.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FollowingService.Migrations
{
    [DbContext(typeof(FollowingContext))]
    partial class FollowingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FollowingService.Model.Entity.Following", b =>
                {
                    b.Property<Guid>("FollowerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FollowingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FollowerId", "FollowingId");

                    b.ToTable("Follows");

                    b.HasData(
                        new
                        {
                            FollowerId = new Guid("eb78bf24-a3ab-48bf-a931-7b0c6e680bfd"),
                            FollowingId = new Guid("34a81ef8-2831-4444-8355-859d02ae2290")
                        },
                        new
                        {
                            FollowerId = new Guid("34a81ef8-2831-4444-8355-859d02ae2290"),
                            FollowingId = new Guid("eb78bf24-a3ab-48bf-a931-7b0c6e680bfd")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
